openapi: 3.0.1
info:
  title: Notes API
  description: An ASP.NET Core Web API for managing Notes
  contact:
    name: Rahma Ahmed
    url: https://github.com/rahma-samaroon
  license:
    name: MIT
    url: https://choosealicense.com/licenses/mit/
  version: v1
paths:
  /api/Notes:
    get:
      tags:
        - Notes
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
    post:
      tags:
        - Notes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
          text/json:
            schema:
              $ref: '#/components/schemas/Note'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Note'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Note'
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
            text/json:
              schema:
                $ref: '#/components/schemas/Note'
  '/api/Notes/{id}':
    get:
      tags:
        - Notes
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Note'
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
            text/json:
              schema:
                $ref: '#/components/schemas/Note'
    put:
      tags:
        - Notes
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
          text/json:
            schema:
              $ref: '#/components/schemas/Note'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Note'
      responses:
        '200':
          description: Success
    delete:
      tags:
        - Notes
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
components:
  schemas:
    Note:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
          nullable: true
        text:
          type: string
          nullable: true
        createdDate:
          type: string
          format: date-time
      additionalProperties: false